name: 'Release'

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        default: ubuntu-22.04
        type: string

jobs:
  publish:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 10

    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.BLE_ACCESS_TOKEN }}
        submodules: true
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Add NuGet source
      run: |
        dotnet nuget add source "${{ env.NUGET_URL }}" \
          --username "${{ secrets.BLE_USERNAME }}" \
          --password "${{ secrets.BLE_ACCESS_TOKEN }}" \
          --store-password-in-clear-text \
          --name github

    - name: Restore dependencies
      run: dotnet restore .

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.15
      with:
        useConfigFile: true
    
    - name: Build
      run: dotnet build -c Release --no-restore . -p:RepositoryUrl=${{ github.server_url }}/${{ github.repository }}
    
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal .

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.BLE_USERNAME }}
        password: ${{ secrets.BLE_ACCESS_TOKEN }}

    - name: Publish and push the container image
      run: dotnet publish --version ${{ env.GitVersion_SemVer }} -c Release /p:PublishProfile=github

    - name: Tag the commit
      run: git tag -f v$GitVersion_SemVer

    - name: Push the tag
      run: git push -f --tags