name: 'Build dev stage'

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        default: ubuntu-22.04
        type: string
    outputs:
      version:
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 10
    outputs:
      version: ${{ steps.versionOutput.outputs.version }}

    steps:
    - name: Prepare
      run: echo "NUGET_URL=https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.BLE_ACCESS_TOKEN }}
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore .

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.15
      with:
        useConfigFile: true
        configFilePath: DariuszGarbarz/Tools/blob/master/GitVersion.yml
    
    - name: Build
      run: dotnet build -c Release --no-restore -p:Version=$GitVersion_SemVer . -p:RepositoryUrl=${{ github.server_url }}/${{ github.repository }}
    
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal .

    - name: Pack
      run: dotnet pack -c Release --no-build -p:Version=$GitVersion_SemVer --verbosity normal .

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: Build/*.nupkg
        retention-days: 5